name: sipeni
description: Sistem Penginputan Nilai KP dan TA UIN SUSKA RIAU.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.8
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
